---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
        - name: jenkins-dir
          mountPath: /var/jenkins_home
      containers:
        - name: jenkins-master
          image: jenkins
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-dir
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-dir
          persistentVolumeClaim:
            claimName: jenkins-master-pvc
